=== Open-Transport/synthese/utils/diff/xsd/synthese-deltas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by Totot (Tutut) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="updatetype">
		<xs:annotation>
			<xs:documentation>Contain all type of update</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Add"/>
			<xs:enumeration value="Delete"/>
			<xs:enumeration value="UpdateData"/>
			<xs:enumeration value="UpdateGeo"/>
			<xs:enumeration value="UpdateAll"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="UpdateTRU_RCSDelta">
		<xs:annotation>
			<xs:documentation>Contain all TRU-RCS objects that have been updated</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="StopPoint" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Trident StopPoint</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="Id" type="xs:string" use="required"/>
					<xs:attribute name="update" type="updatetype"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="ChouetteRoute" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Trident ChouetteRoute</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="Id" type="xs:string" use="required"/>
					<xs:attribute name="update" type="updatetype"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="ConnectionLink" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Trident ConnectionLink</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="Id" type="xs:string" use="required"/>
					<xs:attribute name="update" type="updatetype"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="syntheseDelta" type="UpdateTRU_RCSDelta"/>
</xs:schema>

=== Open-Transport/synthese/utils/diff/doc/example.xml
<?xml version='1.0' encoding='UTF-8'?><syntheseDelta xsi:noNamespaceSchemaLocation="http://www.reseaux-conseil.com/trident/synthese-deltas.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><StopPoint Id="SYNTHESE:StopPoint:2814751795451560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795452560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795453560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795454560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795455560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795456560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795457560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795458560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795459560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795460560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795461560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795462560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795463560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795464560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795465560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795466560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795467560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795468560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795469560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795470560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795471560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795472560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795473560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795474560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795475560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795476560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795477560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795478560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795479560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795479561" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795518560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795519560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795520560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795521560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795522560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795523560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795524560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795525560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795526560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795527560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795528560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795529560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795530560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795531560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795532560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795533560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795534560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795535560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795536560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795537560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795538560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795539560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795540560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795541560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795542560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795543560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795544560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795545560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795546560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795547560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795547561" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795580560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795581560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795582560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795583560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795584560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795585560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795586560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795587560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795588560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795589560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795590560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795591560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795592560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795593560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795594560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795595560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795596560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795597560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795598560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795599560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795600560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795601560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795602560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795603560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795604560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795604561" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795639560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795640560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795641560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795642560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795643560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795644560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795645560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795646560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795647560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795648560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795649560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795650560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795651560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795652560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795653560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795654560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795655560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795656560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795657560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795658560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795659560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795660560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795661560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795662560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795663560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795664560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795665560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795666560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751795666561" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909414560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909415560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909416560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909417560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909418560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909419560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909420560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909421560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909422560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909423560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909424560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909425560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909426560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909427560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909428560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909428561" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909430560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909431560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909432560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909433560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909434560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909435560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909436560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909437560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909438560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909439560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909440560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909441560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909442560" update="Add" /><StopPoint Id="SYNTHESE:StopPoint:2814751909443560" update="Add" /><StopPoint Id="SYNTH
