=== Open-Transport/synthese/doc/include/53_pt_routeplanner/routeplanner_result.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by Romain Hugues (RÃ©seaux Conseil & Solutions) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="routePlannerResult" type="RoutePlannerResultType">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="RoutePlannerResultType">
		<xs:sequence>
			<xs:element name="query" type="QueryType"/>
			<xs:element name="journeys" type="JourneysType"/>
			<xs:element name="resultTable" type="ResultTableType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QueryType">
		<xs:sequence>
			<xs:element name="timeBounds">
				<xs:complexType>
					<xs:attribute name="minDepartureHour" type="xs:dateTime" use="required"/>
					<xs:attribute name="maxDepartureHour" type="xs:dateTime" use="required"/>
					<xs:attribute name="minArrivalHour" type="xs:dateTime" use="required"/>
					<xs:attribute name="maxArrivalHour" type="xs:dateTime" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="timePeriod" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="date" type="xs:date" use="required"/>
					<xs:attribute name="id" type="xs:long" use="required"/>
					<xs:attribute name="name" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="places">
				<xs:complexType>
					<xs:attribute name="departureCity" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="departureCityNameTrust" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:double">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="departureStop">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="departureStopNameTrust">
						<xs:simpleType>
							<xs:restriction base="xs:double">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="arrivalCity" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="arrivalCityNameTrust" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:double">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="arrivalStop">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:minLength value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="arrivalStopNameTrust">
						<xs:simpleType>
							<xs:restriction base="xs:double">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="1"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="favorite" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="id" type="xs:long" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="transportModeFilter" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="id" type="xs:long" use="required"/>
					<xs:attribute name="name" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="siteId" type="xs:long" use="required"/>
		<xs:attribute name="userProfile" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:enumeration value="35001"/>
					<xs:enumeration value="35002"/>
					<xs:enumeration value="35003"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="maxSolutions">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="1"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="sessionId" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="JourneysType">
		<xs:sequence>
			<xs:element name="journey" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="reservation" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="type" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="compulsory"/>
											<xs:enumeration value="optional"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="deadLine" type="xs:dateTime" use="required"/>
								<xs:attribute name="online" type="xs:boolean" use="required"/>
								<xs:attribute name="phoneNumber" type="xs:string"/>
								<xs:attribute name="openingHours" type="xs:string"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="chunks">
							<xs:complexType>
								<xs:choice maxOccurs="unbounded">
									<xs:element name="connection" type="JourneyConnectionType"/>
									<xs:element name="street" type="JourneyStreetType"/>
									<xs:element name="transport" type="JourneyTransportType"/>
								</xs:choice>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="continuousServiceDuration" type="xs:duration"/>
					<xs:attribute name="hasAStopAlert" type="xs:boolean" use="required"/>
					<xs:attribute name="hasALineAlert" type="xs:boolean" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ResultTableType">
		<xs:sequence>
			<xs:element name="row" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="cells">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="cell" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="arrivalDateTime" type="xs:dateTime"/>
											<xs:attribute name="endArrivalDateTime" type="xs:dateTime"/>
											<xs:attribute name="departureDateTime" type="xs:dateTime"/>
											<xs:attribute name="endDepartureDateTime" type="xs:dateTime"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="place" type="PlaceType"/>
					</xs:sequence>
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="departure"/>
								<xs:enumeration value="connection"/>
								<xs:enumeration value="arrival"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="JourneyConnectionType">
		<xs:annotation>
			<xs:documentation>Foot link between two stops without details about the used streets</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="JourneyChunkType">
				<xs:sequence>
					<xs:element name="startStop" type="PhysicalStopType"/>
					<xs:element name="endStop" type="PhysicalStopType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="JourneyStreetType">
		<xs:annotation>
			<xs:documentation>Foot way along a street</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="JourneyChunkType">
				<xs:sequence>
					<xs:element name="startAddress" type="PlaceType"/>
					<xs:element name="endAddress" type="PlaceType"/>
				</xs:sequence>
				<xs:attribute name="city" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="name" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="JourneyTransportType">
		<xs:annotation>
			<xs:documentation>Use of public transportation system</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="JourneyChunkType">
				<xs:sequence>
					<xs:element name="startStop" type="PhysicalStopType"/>
					<xs:element name="endStop" type="PhysicalStopType"/>
					<xs:element name="destinationStop" type="PhysicalStopType"/>
					<xs:element name="line">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="alert" type="AlertType" minOccurs="0"/>
							</xs:sequence>
							<xs:attribute name="id" type="SYNTHESEObjectIdType" use="required"/>
							<xs:attribute name="color"/>
							<xs:attribute name="imgURL" type="xs:string"/>
							<xs:attribute name="cssClass"/>
							<xs:attribute name="shortName"/>
							<xs:attribute name="longName"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="vehicleType" minOccurs="0">
						<xs:complexType>
							<xs:attribute name="id" type="SYNTHESEObjectIdType" use="required"/>
							<xs:attribute name="name"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="possibleWaitingTime" type="xs:duration"/>
				<xs:attribute name="startStopIsTerminus" type="xs:boolean" use="required"/>
				<xs:attribute name="endStopIsTerminus" type="xs:boolean" use="required"/>
				<xs:attribute name="destinationText">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="JourneyChunkType">
		<xs:attribute name="departureTime" type="xs:dateTime" use="required"/>
		<xs:attribute name="endDepartureTime" type="xs:dateTime"/>
		<xs:attribute name="arrivalTime" type="xs:dateTime" use="required"/>
		<xs:attribute name="endArrivalTime" type="xs:dateTime"/>
		<xs:attribute name="length" type="MetersLengthType" use="required"/>
	</xs:complexType>
	<xs:complexType name="PointType">
		<xs:attribute name="x" type="xs:integer"/>
		<xs:attribute name="y" type="xs:integer"/>
		<xs:attribute name="latitude" type="xs:decimal"/>
		<xs:attribute name="longitude" type="xs:decimal"/>
	</xs:complexType>
	<xs:complexType name="PhysicalStopType">
		<xs:complexContent>
			<xs:extension base="PointType">
				<xs:sequence>
					<xs:element name="connectionPlace" type="ConnectionPlaceType"/>
				</xs:sequence>
				<xs:attribute name="id" type="SYNTHESEObjectIdType" use="required"/>
				<xs:attribute name="name" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ConnectionPlaceType">
		<xs:complexContent>
			<xs:extension base="PointType">
				<xs:sequence>
					<xs:element name="alert" type="AlertType" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute name="id" type="SYNTHESEObjectIdType" use="required"/>
				<xs:attribute name="city" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="name" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PublicPlaceType">
		<xs:complexContent>
			<xs:extension base="PointType">
				<xs:attribute name="id" type="SYNTHESEObjectIdType" use="required"/>
				<xs:attribute name="city" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="name" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="AddressType">
		<xs:complexContent>
			<xs:extension base="PointType">
				<xs:attribute name="id" use="required"/>
				<xs:attribute name="city" use="required"/>
				<xs:attribute name="number" type="xs:string"/>
				<xs:attribute name="streetName" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PlaceType">
		<xs:choice>
			<xs:element name="connectionPlace" type="ConnectionPlaceType"/>
			<xs:element name="publicPlace" type="PublicPlaceType"/>
			<xs:element name="address" type="AddressType"/>
		</xs:choice>
	</xs:complexType>
	<xs:simpleType name="SYNTHESEObjectIdType">
		<xs:restriction base="xs:long">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MetersLengthType">
		<xs:annotation>
			<xs:documentation>Length in meters</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AlertType" mixed="true">
		<xs:attribute name="id" type="SYNTHESEObjectIdType" use="required"/>
		<xs:attribute name="level" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="info"/>
					<xs:enumeration value="warning"/>
					<xs:enumeration value="interruption"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="startValidity" type="xs:dateTime"/>
		<xs:attribute name="endValidity" type="xs:dateTime"/>
	</xs:complexType>
</xs:schema>

=== Open-Transport/synthese/doc/include/53_pt_routeplanner/routeplanner_resultSample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<routePlannerResult xsi:noNamespaceSchemaLocation="http://rcsmobility.com/xsd/routeplanner_result.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<query maxSolutions="4" userProfile="35001" sessionId="123456789ABCDE" siteId="7036874417766401">
		<timeBounds minDepartureHour="2001-12-17T09:30:47.0Z" minArrivalHour="2001-12-17T09:30:47.0Z" maxArrivalHour="2001-12-18T09:30:47.0Z" maxDepartureHour="2001-12-18T11:30:47.0Z"/>
		<places departureCity="TOULOUSE" arrivalCityNameTrust="0.9" departureCityNameTrust="0.7" arrivalStopNameTrust="0.8" arrivalStop="Montparnasse" arrivalCity="PARIS" />
		<transportModeFilter id="2147483647" name="Tous modes"/>
	</query>
	<journeys>
		<journey hasALineAlert="true" hasAStopAlert="false">
			<reservation online="true" type="optional" openingHours="Tous les jours" deadLine="2001-12-16T09:30:47.0Z" phoneNumber="String"/>
			<chunks>
				<transport departureTime="2001-12-17T09:30:47.0Z" arrivalTime="2001-12-17T19:30:47.0Z" length="800000" startStopIsTerminus="true" endStopIsTerminus="true" >
					<startStop latitude="0.0" longitude="0.0" id="1" x="0" y="0" name="Quai 1">
						<connectionPlace latitude="0.0" longitude="0.0" id="1" city="TOULOUSE" x="0" y="0" name="Matabiau">
						</connectionPlace>
					</startStop>
					<endStop latitude="0.0" longitude="0.0" id="2" x="0" y="0" name="Quai 26">
						<connectionPlace latitude="0.0" longitude="0.0" id="2" city="PARIS" x="0" y="0" name="Montparnasse">
						</connectionPlace>
					</endStop>
					<destinationStop id="2" x="0" y="0" name="Quai 26">
						<connectionPlace latitude="0.0" longitude="0.0" id="2" city="PARIS" x="0" y="0" name="Montparnasse">
						</connectionPlace>
					</destinationStop>
					<line id="5675" color="#CCCCCC" cssClass="gris" imgURL="tgv.png" longName="le TGV Atlantique" shortName="TGV">
					<alert id="9834" level="interruption" startValidity="2000-01-01T00:00:07.0Z" endValidity="2099-12-31T23:59:00.0Z">SNCF en grève</alert>
					</line>
					<vehicleType id="456" name="TGV" />
				</transport>
			</chunks>
		</journey>
		<journey hasALineAlert="false" hasAStopAlert="true">
			<reservation online="false" type="compulsory" openingHours="Semaine" deadLine="2001-12-17T09:26:47.0Z" phoneNumber="1234"/>
			<chunks>
				<transport endStopIsTerminus="false" length="256000" startStopIsTerminus="true" departureTime="2001-12-17T17:30:47.0Z" arrivalTime="2001-12-17T17:25:47.0Z" possibleWaitingTime="PT5M">
					<startStop latitude="0.0" longitude="0.0" id="1" x="0" y="0" name="String">
						<connectionPlace latitude="0.0" longitude="0.0" id="1" city="a" x="0" y="0" name="a">
						</connectionPlace>
					</startStop>
					<endStop latitude="0.0" longitude="0.0" id="3" x="0" y="0" name="Quai 6">
						<connectionPlace latitude="0.0" longitude="0.0" id="3" city="BORDEAUX" x="0" y="0" name="Saint-Jean">
							<alert id="1444" startValidity="2001-12-10T09:30:47.0Z" endValidity="2002-12-24T09:30:47.0Z" level="info">Travaux sur le parvis de la gare</alert>
						</connectionPlace>
					</endStop>
					<destinationStop latitude="0.0" longitude="0.0" id="3" x="0" y="0" name="Quai 6">
						<connectionPlace latitude="0.0" longitude="0.0" id="3" city="BORDEAUX" x="0" y="0" name="Saint-Jean">
							<alert id="1444" startValidity="2001-12-10T09:30:47.0Z" endValidity="2002-12-24T09:30:47.0Z" level="info">Travaux sur le parvis de la gare</alert>
						</connectionPlace>
					</destinationStop>
					<line id="123456" color="#C00000" cssClass="red" shortName="C" />
					<vehicleType id="123" name="Bus" />
				</transport>
				<street length="600000" city="BORDEAUX" name="Autoroute A10" departureTime="2001-12-17T17:30:47.0Z" arrivalTime="2001-12-17T17:25:47.0Z">
					<startAddress>
						<connectionPlace latitude="0.0" longitude="0.0" id="1" x="0" y="0" city="BORDEAUX"  name="Saint-Jean"><alert id="1444" startValidity="2001-12-10T09:30:47.0Z" endValidity="2002-12-24T09:30:47.0Z" level="info">Travaux sur le parvis de la gare</alert>
						</connectionPlace>
					</startAddress>
					<endAddress>
						<connectionPlace latitude="0.0" longitude="0.0" id="1" city="PARIS" x="0" y="0" name="Montparnasse">
						</connectionPlace>
					</endAddress>
				</street>
			</chunks>
		</journey>
		<journey hasALineAlert="true" hasAStopAlert="false" continuousServiceDuration="PT1H">
			<reservation online="true" type="compulsory" openingHours="String" deadLine="2001-12-17T09:30:47.0Z" phoneNumber="String"/>
			<chunks>
				<transport endStopIsTerminus="false" startStopIsTerminus="true" length="700000" departureTime="2001-12-17T11:30:47.0Z" endDepartureTime="2001-12-17T12:30:47.0Z" arrivalTime="2001-12-17T21:00:47.0Z" endArrivalTime="2001-12-17T22:00:47.0Z">
					<startStop latitude="0.0" longitude="0.0" id="1" x="0" y="0" name="Quai 4">
						<connectionPlace latitude="0.0" longitude="0.0" id="1" city="TOULOUSE" x="0" y="0" name="Matabiau">
						</connectionPlace>
					</startStop>
					<endStop latitude="0.0" longitude="0.0" id="1" x="0" y="0" name="Quai 17">
						<connectionPlace latitude="0.0" longitude="0.0" id="1" city="PARIS" x="0" y="0" name="Austerlitz">
						</connectionPlace>
					</endStop>
					<destinationStop latitude="0.0" longitude="0.0" id="1" x="0" y="0" name="Quai 17">
						<connectionPlace latitude="0.0" longitude="0.0" id="1" city="PARIS" x="0" y="0" name="Austerlitz">
						</connectionPlace>
					</destinationStop><line id="4599" color="#435863" shortName="10" ></line>
					<vehicleType id="03493" name="Métro" />
				</transport>
				<connection length="0" departureTime="2001-12-17T21:00:47.0Z" arrivalTime="2001-12-17T21:30:47.0Z" endDepartureTime="2001-12-17T22:00:47.0Z" endArrivalTime="2001-12-17T22:30:47.0Z">
					<startStop latitude="0.0" longitude="0.0" id="1" x="0" y="0" name="Parvis">
						<connectionPlace latitude="0.0" longitude="0.0" id="1" city="PARIS" x="0" y="0" name="Austerlitz">
						</connectionPlace>
					</startStop>
					<endStop latitude="0.0" longitude="0.0" id="1" x="0" y="0" name="Parvis">
						<connectionPlace latitude="0.0" longitude="0.0" id="1" city="PARIS" x="0" y="0" name="Montparnasse">
						</connectionPlace>
					</endStop>
				</connection>
			</chunks>
		</journey>
	</journeys>
	<resultTable>
		<row type="departure">
			<cells>
				<cell departureDateTime="2001-12-17T09:30:47.0Z" />
				<cell departureDateTime="2001-12-17T10:30:47.0Z" />
				<cell departureDateTime="2001-12-17T11:30:47.0Z" endDepartureDateTime="2001-12-17T12:30:47.0Z" />
			</cells>
			<place>
				<connectionPlace latitude="0.0" longitude="0.0" id="1" city="a" x="0" y="0" name="a">
				</connectionPlace>
			</place>
		</row>
		<row type="connection">
			<cells>
				<cell />
				<cell departureDateTime="2001-12-17T17:30:47.0Z" arrivalDateTime="2001-12-17T17:25:47.0Z" />
				<cell />
			</cells>
			<place>
				<connectionPlace latitude="0.0" longitude="0.0" id="1" city="BORDEAUX" x="0" y="0" name="Saint-Jean">
					<alert id="1444" startValidity="2001-12-17T07:30:47.0Z" endValidity="2002-12-17T09:30:47.0Z" level="warning">Travaux sur le parvis de la gare</alert>
				</connectionPlace>
			</place>
		</row>
		<row type="connection">
			<cells>
				<cell />
				<cell />
				<cell departureDateTime="2001-12-17T21:00:47.0Z" arrivalDateTime="2001-12-17T21:00:47.0Z" endArrivalDateTime="2001-12-17T22:00:47.0Z"  endDepartureDateTime="2001-12-17T22:00:47.0Z"/>
			</cells>
			<place>
				<connectionPlace latitude="0.0" longitude="0.0" id="1" city="PARIS" x="0" y="0" name="Austerlitz">
				</connectionPlace>
			</place>
		</row>
		<row type="arrival">
			<cells>
				<cell arrivalDateTime="2001-12-17T19:30:47.0Z" />
				<cell arrivalDateTime="2001-12-17T20:30:47.0Z" />
				<cell arrivalDateTime="2001-12-17T21:30:47.0Z" endArrivalDateTime="2001-12-17T22:30:47.0Z"/>
			</cells>
			<place>
				<connectionPlace latitude="0.0" longitude="0.0" id="1" city="PARIS" x="0" y="0" name="Montparnasse">
				</connectionPlace>
			</place>
		</row>
	</resultTable>
</routePlannerResult>
